language: cpp

script:
  - cmake .
  - cmake --build .
 // - cmake --build . --target test
  - cmake --build . --target package

deploy:
  provider: script

  skip_cleanup: true

  script:
  - curl -T hello-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ubarion2018:$BINTRAY_API_KEY "https://api.bintray.com/content/barion2018/DebianHW1/DebHW1_2/hello-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
 

